### ISSUE TITLE
'NoneType' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by tanklandry** [ydli-ai/Chinese-ChatLLaMA#25]
TencentPretrain/tencentpretrain/utils/dataloader.py", line 187, in __iter__
    yield torch.LongTensor(src), \
TypeError: 'NoneType' object cannot be interpreted as an integer   请问这个是什么问题导致的，貌似预处理后的文件也没问题

**Comment by ydli-ai** [comment]
# 修改 utils/constants.py 文件L4，将 special_tokens_map.json 改为 llama_special_tokens_map.json
