### ISSUE TITLE
按照 README.md 来根本跑不出预期的效果

### ISSUE THREAD

**Issue by ToSev7en** [ydli-ai/Chinese-ChatLLaMA#3]

**Comment by ydli-ai** [comment]
有运行参数或者示例吗

**Comment by dtxwhzw** [comment]
> 有运行参数或者示例吗

用python3 scripts/generate_lm.py --load_model_path ../ChineseChatLLaMA//ChatLLaMA_7B.bin --spm_model_path ../ChineseChatLLaMA/tokenizer.model \
                                --test_path beginning.txt --prediction_path generated_sentence.txt \
                               --config_path models/llama/7b_config.json --seq_length 512
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/38512349/228828217-868b5cdd-dedb-49b6-b4b4-f81fc98c9af2.png">

**Comment by 15810856129** [comment]
![image](https://user-images.githubusercontent.com/31722283/228829191-c8bbe4df-ecd5-4d28-9af9-93fba549b943.png)
我这生成出来是乱码还是，看着这么别扭呢？

**Comment by dtxwhzw** [comment]
> > 另外用python3 scripts/generate_lm_deepspeed.py 命令运行会得到以下错误，请问下是什么原因 <img alt="image" width="1351" src="https://user-images.githubusercontent.com/38512349/228832729-77548a27-7dfa-49fa-ac06-32b0b8b1165d.png">
> 
> deepspeed版本太新了，降回0.8.2就行

降版本没啥用，还是这个问题

**Comment by louisxavier123** [comment]
> > > 另外用python3 scripts/generate_lm_deepspeed.py 命令运行会得到以下错误，请问下是什么原因 <img alt="image" width="1351" src="https://user-images.githubusercontent.com/38512349/228832729-77548a27-7dfa-49fa-ac06-32b0b8b1165d.png">
> > 
> > 
> > deepspeed版本太新了，降回0.8.2就行
> 
> 降版本没啥用，还是这个问题

试试多降几个？我现在降到0.7.0就行了

**Comment by ydli-ai** [comment]
已更新，用新的脚本再试一下

**Comment by ydli-ai** [comment]
已解决，更新 generate_chatllama.py
