### ISSUE TITLE
generate_chatllama.py 86行应该去掉True

### ISSUE THREAD

**Issue by louisxavier123** [ydli-ai/Chinese-ChatLLaMA#4]
如果使用你的参数会出现以下错误：
TypeError: load_model() takes 2 positional arguments but 3 were given
可以改为：
model = load_model(model, args.load_model_path)
因为在model_loader.py文件里，函数只需要两个输入：
def load_model(model, model_path)
可以改一下谢谢

**Comment by ydli-ai** [comment]
已修复
